services:
  # Base de Datos
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: db_posts
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: posts_app_pass*2025
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db_posts"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend
  backend:
    build: ./backend_posts_app
    container_name: express-backend
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: db_posts
      DB_USER: admin
      DB_PASSWORD: posts_app_pass*2025
    ports:
      - "3001:3001"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build: ./frontend_posts_app
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Nginx
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: